services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      FLASK_APP: app:create_app
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
    volumes:
      - ./backend:/app
      - ./backend/coins.db:/app/coins.db
    ports:
      - "5000:5000"
    command: sh -c "flask db upgrade && flask run"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    command: npm run dev

